// SPDX-FileCopyrightText: 2026 Mise contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

plugins {
    id 'com.android.application' version '9.4.0' apply false
    id 'org.jetbrains.kotlin.android' version '2.2.0' apply false
    id 'org.jetbrains.kotlin.plugin.compose' version '2.2.0' apply false
}

apply from: "variables.gradle"

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
